server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lostandfound?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lzx2983286
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
